package com.tinqin.financialManagementProject.api.paymentsFile.removeInvoiceForPayment;

import com.tinqin.financialManagementProject.api.base.OperationProcessor;

public interface RemoveInvoiceForPaymentOperation extends OperationProcessor<RemoveInvoiceForPaymentRequest, RemoveInvoiceForPaymentResponse> {
}
